name: CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "master"

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.6", "8.8", "8.10", "9.0", "9.2"]

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Build
      run: |
        cabal v2-update
        cabal v2-build --enable-tests --enable-benchmarks

    - name: Test
      run: |
        cabal v2-test --enable-tests
