name: Haskell CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "master"

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ghc: [ "8.8.3", "8.10.2", "9.0.1" ]
        cabal: ["3.2.0.0"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: haskell/actions/setup
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Install dependencies
      run: |
        cabal new-update
        cabal new-configure --enable-tests --write-ghc-environment-files=always -j2
        cabal new-build --only-dependencies
    - name: Build & test
      run: |
        cabal v2-build
        cabal new-test --enable-tests
