name: Haskell CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "master"

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.2.2", "8.4.4", "8.6.5", "8.8.4", "8.10.4", "9.0.1", "9.2.1"]
        cabal: ["3.2"]

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1.1.8
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v2
      name: Cache ~/.cabal/packages
      with:
        path: ~/.cabal/packages
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages
    - uses: actions/cache@v2
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store
    - uses: actions/cache@v2
      name: Cache dist-newstyle
      with:
        path: dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-fused-effects-dist

    - name: Install dependencies
      run: |
        cabal v2-update
        cabal v2-configure --enable-benchmarks --enable-tests --write-ghc-environment-files=always -j2
        cabal v2-build     --only-dependencies all

    - name: Build & test
      run: |
        cabal v2-build
